### ISSUE TITLE
Изменить описание

### ISSUE THREAD

**Issue by andchir** [Platron/module_modx_revolution_shopkeeper#1]
В описании у вас написано "for MODX Revolution Shopkeeper 2.3.10". Но, судя по коду, данный компонент должен работать на Shopkeeper 3.x. Прошу изменить описание, если это так.

**Comment by lashnag** [comment]
Прошу прощения, за столь длительный ответ. Подскажите - где вы видели это описание? В самом модуле его нет. И по идее должно быть написано - что тестировалось для модуля, а не для какого работает. А это разные вещи

**Comment by andchir** [comment]
В описании этого репозитория https://github.com/Platron/module_modx_revolution_shopkeeper
Цитата: "Payment module Platron for MODX Revolution Shopkeeper 2.3.10"

https://github.com/Platron/module_modx_revolution_shopkeeper/blob/master/platron/elements/snippets/snippet.platron.php#L15
Здесь берется объект "shk_order", такой есть только в Shopkeepr 3.x
https://github.com/andchir/shopkeeper3/blob/master/core/components/shopkeeper3/model/shopkeeper3/shk_order.class.php

**Comment by lashnag** [comment]
https://github.com/Platron/module_modx_revolution_shopkeeper/search?q=Payment+module+Platron&unscoped_q=Payment+module+Platron - это ссылка на поиск по репозиторию. Возможно, это у Вас отображается в админке modx и как-то генерируется автоматически или в каком-то маркетплейсе вы нашли это описание? Потому, что в самом репозитории я не нашел даже упоминания версии 2.3.10

**Comment by andchir** [comment]
Скриншот: https://www.dropbox.com/s/hwjxz1n3f36e0xn/screenshot_016.png?dl=0

**Comment by lashnag** [comment]
Понял, это в настройках репозитория было - не в коде. Спасибо!
